services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: transituser
      POSTGRES_PASSWORD: transitpassword
      POSTGRES_DB: transitdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transituser -d transitdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://transituser:transitpassword@db:5432/transitdb"
      PORT: 3000
    entrypoint: /app/entrypoint.sh

volumes:
  postgres_data:
